[window]
opacity = 0.75
dynamic_padding = true

[font]
normal = { family = "ProFontWindows Nerd Font Propo", style = "Regular" }
size = 12

[cursor]
style = { shape = "Underline", blinking = "Never" }
